GRANT ALL PRIVILEGES ON DATABASE perchmerch TO perchmerchuser;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO perchmerchuser;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO perchmerchuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO perchmerchuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO perchmerchuser;